### ISSUE TITLE
lists with outdated URL's...

### ISSUE THREAD

**Issue by dnmTX** [Ultimate-Hosts-Blacklist/dev-center#7] opened 2018-08-21 05:45 UTC
@funilrys  there are three lists so far that i've encounter which moved their repos to GitLab, very much active with at least one weekly update and **here** and in **dead-hosts** you still using the old URL's from GitHub which are outdated to say the least.If you don't mind look in to it.I'd rather download those lists from here but knowing that they're outdated is a big NO NO for me:

https://github.com/Ultimate-Hosts-Blacklist/quidsup_notrack_trackers
https://github.com/Ultimate-Hosts-Blacklist/quidsup_malicious-sites
New URL:
https://gitlab.com/quidsup/notrack-blocklists

https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists
New URL:
https://gitlab.com/ZeroDot1/CoinBlockerLists

Thank you.

P.S. Another thought...on **active lists** like the one mentioned above or any other the `domain.list` needs to be updated more often,like at least once weekly(don't want to push it but twice weekly sounds even better 🙂)

**Comment by funilrys** [comment] 2018-08-22 15:37
Hi @dnmTX thanks for reporting will update the links asap.

About the `domain.list`, if the upstream link is update it is also updated...

Have a nice day/night.

**Comment by dnmTX** [comment] 2018-08-22 18:50
> About the domain.list, if the upstream link is update it is also updated...

**Comment by funilrys** [comment] 2018-08-25 17:38
Hi @dnmTX, 
As referenced, this issue is partially fixed.

**Comment by mitchellkrogza** [comment] 2018-08-26 06:42
I think we need some logic in PyFunceble that if a domain was inactive once and became active again we mark it as suspicious and keep it on active?

**Comment by funilrys** [comment] 2018-09-09 13:51
Hi @dnmTX,
if there is no changes in the tests it's normal that it is not updating.

**Comment by funilrys** [comment] 2018-09-21 20:58
https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists_optional and https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists_browser created.

Closing.

**Closed by funilrys** 2018-09-21 20:58 UTC
Labels: bug, enhancement

**Comment by dnmTX** [comment] 2018-09-21 23:02
@funilrys  consider changing `CoinBlockerLists_optional` with [hosts](https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/hosts). I think the `optional` one is the one that is more aggressive and have more false positives.The `hosts` one covers wider area and it gives you better protection then the `browser` one in general(i personally using it on my end).

**Comment by funilrys** [comment] 2018-09-22 07:08
In Detail @dnmTX.

Please report to 
* https://github.com/Ultimate-Hosts-Blacklist/quidsup_notrack_trackers/blob/master/info.json#L10
* https://github.com/Ultimate-Hosts-Blacklist/quidsup_malicious-sites/blob/master/info.json#L10
* https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/templates/README_template.md#credits--thanks

The system will do its work automatically and correctly once the repository will have an execution time from Travis CI.

| Repository                                                           | Next session in |
|----------------------------------------------------------------------|-----------------|
| https://github.com/Ultimate-Hosts-Blacklist/quidsup_notrack_trackers | 7h              |
| https://github.com/Ultimate-Hosts-Blacklist/quidsup_malicious-sites  | 7h              |



I do not understand what you say. 

| Repo                                                                           | Tested                                                                    |
|--------------------------------------------------------------------------------|---------------------------------------------------------------------------|
| https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists          | https://zerodot1.gitlab.io/CoinBlockerLists/list.txt                      |
| https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists_browser  | https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list_browser.txt  |
| https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists_optional | https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list_optional.txt |

**Comment by funilrys** [comment] 2018-09-22 07:27
Also, our whole organization ([Ultimate-Hosts-Blacklist](https://github.com/Ultimate-Hosts-Blacklist)) - except for special repositories - has for purpose to test input source and provide the `clean.list`. The whole process is done automatically.

Understand that this organization is only the backend of the main repository [mitchellkrogza/Ultimate.Hosts.Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist).

Everyday at `T14:06:39Z` the generation of the unified hosts file is started. What it does it getting the list of all repository of this organization from the GitHub API then get `clean.list` or `domains.list` if `clean.list` is not found.

As we need many IP to have consistent test for long list, we choose by design to use Travis CI which is great as it's offer a free usage for open repository. To understand why the repository are not updated right in the way, you have to understand that Travis CI only allow us to run 5 instances at the same time. 

We are aware that our system provide some stress to the Travis CI team and infrastructure as our system is maybe one of those rare who run almost 24/24/7 that's why we accept those 5 instances limitation.

In order to allow bigger list to run stright away when they are under test, we implemented a code side "switch".
Indeed, as some upstream may not be update their list every day we also have the `days_until_next_test` in order to stop the system right before it test if the number of day < `days_until_next_test`. 

Therefor if you find that `days_until_next_test` is not realistic for a repository let me know, I will check and update if needed.

I hope that this clarify what was misunderstood (if something was actually misunderstood).

Cheers,
Nissar

**Comment by dnmTX** [comment] 2018-09-22 08:12
@funilrys  this is what misled me:
![test](https://user-images.githubusercontent.com/34774426/45915104-c778b480-be14-11e8-9b7c-86e910d2ad5a.png)

Makes the impression that still the old URL's are in use.Obviously my mistake,sorry for the confusion,basically disregard my last post.Thank you for that in detail explanation.
Cheers!
