### ISSUE TITLE
[suggestion] couple new lists for consideration 

### ISSUE THREAD

**Issue by dnmTX** [Ultimate-Hosts-Blacklist/dev-center#8] opened 2018-09-22 18:13 UTC
@funilrys  consider adding  [anudeepND lists](https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt) @anudeepND is very active player on the hosts blocking scene,he definitely could use the help filtering the lists.

I saw you added [DShield lists-Low](https://github.com/Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List) there are two more if you want to take a look: 
[Medium](https://www.dshield.org/feeds/suspiciousdomains_Medium.txt)
[High](https://www.dshield.org/feeds/suspiciousdomains_High.txt)
Let me know what you think.Thanks

**Comment by funilrys** [comment] 2018-10-24 20:14
I would really like to do better not but it may take some time as I have to study, work, live with family and girlfriend and in my free time develop the different tools and system to make @dead-hosts and @Ultimate-Hosts-Blacklist better with the help of a sort of intelligence for the maintenance and monitoring.

Again @dnmTX you have to understand that we are dependent on Travis CI because we are not really ready to invest more that we get for this project.  We have more that 50 input sources that have to cleaned and Travis CI can run 5 instance of 10 minutes at the same time. That make some build/test long enough to least day

Desperate the fact that Travis CI claim to be stable, we often have to get in the middle to restart the build because Travis containers have issue for x or y reasons which are obscure and not dependent from the system and script we wrote.

Back to the problem you mention, you have to understand that we test the file then we get a fresh copy. Indeed, while testing for bigger list (as example) if I will start from the beginning directly because the upstream link was updated, you'll never get a `clean.list`. 
That means that if Travis has an obscure bug, we wait 24h before continuing were we stopped because the cronjobs cannot be programmed (under Travis CI) for a time under 24h.
There is indeed a way to bypass that but it has to be an external system which run in one of our machine (which run 24/24/7). That's what I actually do on my free time after the development for roadmap and objectives in other OSP I maintain or contribute.

I'll do my best to find why there is so much inconstant in the build history and will come back to you around the weekend.

I agree that we should be more proactive but it will mean that we are monitoring the whole system 24/24/7. Which is quiet impossible for us (@mitchellkrogza and I) that's why I'm working on tool to do the monitoring and maintenance automatically. That tool will not only monitor and maintain @Ultimate-Hosts-Blacklist or @dead-hosts, but also all of the repository we maintain (again @mitchellkrogza  and I) which run with PyFunceble and Travis CI. That's why you may have to wait a bit.

If you can't live because of those limitation, I'll then invite you to download PyFunceble, deactivate de usage of the WHOIS record if you use it for your personal usage and test the list directly for your need. 

Otherwise, please be patient it will be better over time, we are just at the beginning of one of our biggest adventure.

Thanks again for the issue reporting.

Cheers,
Nissar

**Comment by funilrys** [comment] 2018-10-28 16:01
It was definitely a Travis CI issue @dnmTX. Indeed, our script was working perfectly but Travis CI was unable to commit push the final commit for an unknown reason which causes in most of our input an endless loop as the test was finished but the commit wasn't pushed. 

The system tried to push again, again and again until it was working. In the middle some days past which caused the issues you mentioned.

I'll generate a new GitHub token for each input source and restart all of them from the beginning (manually) asap and monitor them manually for some hours to confirm that the issue is now gone.

Cheers,
Nissar

**Comment by funilrys** [comment] 2018-10-28 17:06
Restarting process :heavy_check_mark: 
Let's monitor now!

**Comment by funilrys** [comment] 2018-10-28 20:09
@dnmTX FYI, after monitoring the first 30 input sources who finished nothing reported :+1:

**Comment by dnmTX** [comment] 2018-10-28 20:33
@funilrys  great.I'll keep an eye on them during the week just in case and if anything i'll let you know.

**Comment by dnmTX** [comment] 2018-11-02 17:40
@funilrys  still happening in anudeepND's list. Filtering is done and there are `26836 lines` in `hosts/ACTIVE` 
 and `24127 lines` in `clean.list`. Just letting you know as i promised,that's all.

**Comment by funilrys** [comment] 2018-11-02 18:52
@dnmTX ==> #12 :smile_cat:

**Comment by dnmTX** [comment] 2018-11-11 07:46
@funilrys  i think [justdomains](https://github.com/Ultimate-Hosts-Blacklist/justdomains_mirror1.malwaredomains.com) is stuck on filtering.It shows that it's still under test but the last commit was two days ago and the lists are not being updated.Just reporting as i'm not sure you're aware or not.

**Comment by funilrys** [comment] 2018-11-11 18:00
Hi, @dnmTX thanks for pointing out.
I traced the error and I can tell that it is because of the cross-repository configuration which was not updated. 

It's now fixed and I added it to my internal workflow for checking and improvements.

Indeed, the system has a cross-repository configuration file which is located here https://github.com/Ultimate-Hosts-Blacklist/repository-structure/blob/master/.PyFunceble_cross_input_sources.yaml. 

What we actually do is:
* Pulling that file and parse it into the local tree so that PyFunceble detect it automatically. 
  * The cross-repository configuration itself is updated every 24 hours.
* Then launch the test/filtering.

What did go wrong:
* The system did pull the cross-repository configuration.
* PyFunceble did not found a newly added index into the configuration file ([cf](https://travis-ci.org/Ultimate-Hosts-Blacklist/justdomains_mirror1.malwaredomains.com/builds/453282946#L514)).
  * Indeed, we chose by design to use [`PyFunceble-dev`](https://pypi.org/project/PyFunceble-dev/) so that every bug of our testing/filtering tools can be found faster than usual in another place because we are testing a big amount of almost random data.
* The test/filtering has to wait until its next cronjob run.

How can we ensure that it will not happen again:
* Actually we can't because of the Travis CI cronjob limitation of 24 hours.
* It will be fixed with the system I'm building which I talked about previously elsewhere.
*  [`PyFunceble-dev`](https://pypi.org/project/PyFunceble-dev/) will be soon (hopefully before the end of the month) released as the stable version.
    * It will drastically reduce such issues as every lines has been reviewed recently and almost every anonymous logs I got into the [Logs sharing](https://pyfunceble.readthedocs.io/en/dev/logs-sharing.html) backend are fixed or will be fixed in the coming days. 

Have a nice day/night.

Cheers,
Nissar

**Closed** 2018-12-02 00:34 UTC
